### ISSUE TITLE
data/VV  No such file or directory problem

### ISSUE THREAD

**Issue by suatcoskun** [isce-framework/dolphin#477]
When i tried to run dolphin i took tihs error:

Traceback (most recent call last):
  File "/home/suat/miniforge3/envs/dolphin-env/bin/dolphin", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/suat/miniforge3/envs/dolphin-env/lib/python3.12/site-packages/dolphin/cli.py", line 32, in main
    run_func(**arg_dict)
.
.
.

RuntimeError: NETCDF:"/media/suat/demir3/dolphin/dolphin/input_slcs/OPERA_L2_CSLC-S1_T071-151229-IW2_20240911T135300Z_20241012T053434Z_S1A_VV_v1.1.h5":"//data/VV": No such file or directory

Any advice?

**Comment by scottstanie** [comment]
Hi, two questions-

1. What happens when you run gdalinfo on that NETCDF string? Does the file exist and is it recognized?
2. Is that directory a mounted directory on your computer that is symlinked somewhere else?

**Comment by suatcoskun** [comment]
İf I give you some extra information:

1. Q:  I installed Dolphin on my external ssd (media, not internal ssd) and tried running it there.
2. Q: When I run gdalinfo on my external ssd  (media) l get an error message but if tried to run it on my internal ssd (home) everything looks good.

Maybe I tried to install Dolphin on my internal ssd and try to rerun it.

Best.

![Screenshot from 2024-11-02 23-13-49](https://github.com/user-attachments/assets/a3c1d50e-dbeb-43c9-8150-ceaa000425ef)

**Comment by scottstanie** [comment]
Ok that's pretty weird haha. 
It seems like this might not be a `dolphin` problem, but something with python/gdal and `/media` drive... That said, i'll turn this into a discussion, since a similar problem with `/media` also came up here: https://github.com/isce-framework/dolphin/issues/405#issuecomment-2331829320 
I'm interested to know what about these python installations can go wrong on ubuntu like this
