### ISSUE TITLE
Error in testing the "Dolphin basic walkthrough" on Google Colab

### ISSUE THREAD

**Issue by Shima-shoki** [isce-framework/dolphin#501]
Hi, I'was really interested in Dophin project so I'm testing the basic InSAR processing by following the "Dolphin basic walkthrough" descriptions on Google Colab. **[I could run the processes until "dolphin run dolphin_config.yaml" part, but it return a list of errors.]([dolphin.log](https://github.com/user-attachments/files/17958002/dolphin.log))** The Python commands are listed below (basically just a copy & paste of the example except some directory name changes). The data are stored on the Colab's disk (not mounted drive). Based on the error massages, my guess is that something is wrong with the I/O of the gdal at an interferogram generation step, but I haven't been able to fix the issue by myself since I'm quite new to this field. Do I also need to install additional software, such as ISCE3 for the interferogram generation? Any help is very much appreciated!

The generated yaml file and the log file are available from this zipfile: [dolphin_config_log.zip](https://github.com/user-attachments/files/17958016/dolphin_config_log.zip)

```python
!pip install dolphin
!pip install opera-utils asf_search
!pip install snaphu
import dolphin
import getpass
import subprocess
from os import chdir
from pathlib import Path
import opera_utils.download
import os
import snaphu
dolphin.show_versions()
```
dolphin version: 0.34.0

Python deps:
        h5py: 3.12.1
         jax: 0.4.33
       numba: 0.60.0
       numpy: 1.26.4
 opera-utils: 0.14.0
    pydantic: 2.9.2
      pyproj: 3.7.0
    rasterio: 1.4.2
 ruamel_yaml: None
       scipy: 1.13.1
threadpoolctl: 3.5.0
        tqdm: 4.66.6
  osgeo.gdal: 3.6.4

System:
      python: 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0]
  executable: /usr/bin/python3
     machine: Linux-6.1.85+-x86_64-with-glibc2.35
Unwrapping packages:
      snaphu: 0.4.1
       spurt: None
       isce3: None
       tophu: None
   whirlwind: None
optional GPU info:
         jax: 0.4.33
gpu_is_available: False

```python
#Set workdir
os.makedirs("workdir_Dolphin", exist_ok=True)
os.chdir("workdir_Dolphin")
```

```python
asf_username = input("Enter your ASF username: ")
asf_password = getpass.getpass("Enter ASF Password: ")
aoi = (
    "POLYGON((-102.8136 31.3039,-102.5927 31.3039,-102.5927 31.532,-102.8136"
    " 31.532,-102.8136 31.3039))"
)
results, options = opera_utils.download.search_cslcs(
    aoi_polygon=aoi,
    # We want to have the same set of dates for each Burst ID (spatial footprint)
    check_missing_data=True,
    track=78,
    start="2021-06-01",
    end="2022-06-01",
)
best_option = options[0]

slc_dir = Path("input_slcs")
slc_dir.mkdir(exist_ok=True)
url_file = slc_dir / "urls.txt"
with open(url_file, "w") as f:
    f.write("\n".join(best_option.inputs))

chdir(slc_dir)
# Download 4in parallel
subprocess.run(
    f"wget --user {asf_username} --password {asf_password} $(cat urls.txt | tr '\n'"
    " ' ')",
    shell=True,
    check=True,
    stdout=subprocess.DEVNULL,
    stderr=subprocess.DEVNULL,
)
chdir('..')
```
```python
!ls input_slcs | head -3
```
OPERA_L2_CSLC-S1_T078-165573-IW2_20210606T005130Z_20240726T084639Z_S1B_VV_v1.1.h5
OPERA_L2_CSLC-S1_T078-165573-IW2_20210618T005131Z_20240726T114540Z_S1B_VV_v1.1.h5
OPERA_L2_CSLC-S1_T078-165573-IW2_20210630T005131Z_20240726T145129Z_S1B_VV_v1.1.h5
```python
!dolphin config --slc-files input_slcs/*.h5 --subdataset "/data/VV"
```
Saving configuration to dolphin_config.yaml
```python
# TQDM doesn't play nicely with notebook outputs, not like terminal
os.environ["TQDM_DISABLE"] = "1"

# Running from the command line
!dolphin run dolphin_config.yaml
```

[INFO|displacement|L108] 2024-11-29T10:24:34+0000: Found SLC files from 2 bursts
[INFO|wrapped_phase|L63] 2024-11-29T10:24:34+0000: Running wrapped phase estimation in /content/workdir_Dolphin/t078_165573_iw2
Traceback (most recent call last):
  File "/usr/local/bin/dolphin", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/dolphin/cli.py", line 32, in main
    run_func(**arg_dict)
  File "/usr/local/lib/python3.10/dist-packages/dolphin/workflows/_cli_run.py", line 32, in run
    displacement.run(cfg, debug=debug)
  File "/usr/local/lib/python3.10/dist-packages/dolphin/_log.py", line 92, in wrapper
    result = f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/dolphin/workflows/displacement.py", line 160, in run
    fut_to_burst = {
  File "/usr/local/lib/python3.10/dist-packages/dolphin/workflows/displacement.py", line 161, in <dictcomp>
    exc.submit(
  File "/usr/local/lib/python3.10/dist-packages/dolphin/utils.py", line 685, in submit
    result = fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/dolphin/_log.py", line 92, in wrapper
    result = f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/dolphin/workflows/wrapped_phase.py", line 87, in run
    mask_filename = _get_mask(
  File "/usr/local/lib/python3.10/dist-packages/dolphin/workflows/wrapped_phase.py", line 512, in _get_mask
    masking.combine_mask_files(
  File "/usr/local/lib/python3.10/dist-packages/dolphin/masking.py", line 86, in combine_mask_files
    xsize, ysize = io.get_raster_xysize(mask_files[0])
  File "/usr/local/lib/python3.10/dist-packages/dolphin/io/_core.py", line 261, in get_raster_xysize
    ds = _get_gdal_ds(filename)
  File "/usr/local/lib/python3.10/dist-packages/dolphin/io/_core.py", line 89, in _get_gdal_ds
    return gdal.Open(filename)
  File "/usr/local/lib/python3.10/dist-packages/osgeo/gdal.py", line 4716, in Open
    return _gdal.Open(*args)
RuntimeError: not a string

**Comment by scottstanie** [comment]
Also just checking that it was on purpose to remove the `--strides` part of the configuration before running: using `--strides 6 3` outputs at 30 meter resolution, but also runs a bunch faster (and has lower memory). 
Yo ucan still run it to output 5 meter x 10 meter, but you might have to lower the `block-shape` on Colab - I haven't tried on Colab at the higher posting

**Comment by scottstanie** [comment]
looks like version 0.34.1 went through:

<img width="1386" alt="image" src="https://github.com/user-attachments/assets/fbebc177-b1fc-496b-ab50-1976d8635a88">

**Comment by Shima-shoki** [comment]
@scottstanie 
Thank you very much for the prompt response about the issue. I also tested with the updated dolphin version and the code went through!
