### ISSUE TITLE
ValueError: Not files have same raster (x, y) size:{(25401, 1509), (25483, 1509), (25482, 1509), (25364, 1509), (25167, 1509), (25168, 1509)}

### ISSUE THREAD

**Issue by songzwgithub** [isce-framework/dolphin#515]
When I did [dolphin run dolphin_config.yaml] action, I noticed [ValueError: Not files have same raster (x, y) size]
```
dolphin run dolphin_config.yaml
[INFO|wrapped_phase|L63] 2024-12-15T05:47:28+0800: Running wrapped phase estimation in /media/s/dolphin
Traceback (most recent call last):
  File "/home/s/anaconda3/envs/sentinel/bin/dolphin", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/s/anaconda3/envs/sentinel/lib/python3.12/site-packages/dolphin/cli.py", line 32, in main
    run_func(**arg_dict)
  File "/home/s/anaconda3/envs/sentinel/lib/python3.12/site-packages/dolphin/workflows/_cli_run.py", line 30, in run
    displacement.run(cfg, debug=debug)
  File "/home/s/anaconda3/envs/sentinel/lib/python3.12/site-packages/dolphin/_log.py", line 90, in wrapper
    result = f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "/home/s/anaconda3/envs/sentinel/lib/python3.12/site-packages/dolphin/workflows/displacement.py", line 161, in run
    exc.submit(
  File "/home/s/anaconda3/envs/sentinel/lib/python3.12/site-packages/dolphin/utils.py", line 684, in submit
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/s/anaconda3/envs/sentinel/lib/python3.12/site-packages/dolphin/_log.py", line 90, in wrapper
    result = f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "/home/s/anaconda3/envs/sentinel/lib/python3.12/site-packages/dolphin/workflows/wrapped_phase.py", line 71, in run
    vrt_stack = VRTStack(
                ^^^^^^^^^
  File "/home/s/anaconda3/envs/sentinel/lib/python3.12/site-packages/dolphin/io/_readers.py", line 742, in __init__
    _assert_images_same_size(self._gdal_file_strings)
  File "/home/s/anaconda3/envs/sentinel/lib/python3.12/site-packages/dolphin/io/_readers.py", line 999, in _assert_images_same_size
    raise ValueError(msg)
ValueError: Not files have same raster (x, y) size:
{(25401, 1509), (25483, 1509), (25482, 1509), (25364, 1509), (25167, 1509), (25168, 1509)}
```

<details>

dolphin config --slc-files slc/*tiff --output-bounds 94.7 29.56 95.67 29.87
[](input_options:
  # If passing HDF5/NetCDF files, subdataset to use from CSLC files. .
  #   Type: string | null.
  subdataset:
  # Format of dates contained in CSLC filenames.
  #   Type: string.
  cslc_date_fmt: '%Y%m%d'
  # Radar wavelength (in meters) of the transmitted data. used to convert the units in the
  #   rasters in `timeseries/` to from radians to meters. If None and sensor is not
  #   recognized, outputs remain in radians.
  #   Type: number | null.
  wavelength:
# Mask file used to ignore low correlation/bad data (e.g water mask). Convention is 0 for no
#   data/invalid, and 1 for good data. Dtype must be uint8.
#   Type: string | null.
mask_file:
# Name of sub-directory to use for writing output files.
#   Type: string.
work_directory: /media/s/新加卷1/dolphin
# Don't resolve filepaths that are given as relative to be absolute.
#   Type: boolean.
keep_paths_relative: false
worker_settings:
  # Whether to use GPU for processing (if available).
  #   Type: boolean.
  gpu_enabled: false
  # Number of threads to use per worker. This sets the OMP_NUM_THREADS environment variable in
  #   each python process.
  #   Type: integer.
  threads_per_worker: 16
  # If processing separate spatial bursts, number of bursts to run in parallel for wrapped-
  #   phase-estimation.
  #   Type: integer.
  n_parallel_bursts: 1
  # Size (rows, columns) of blocks of data to load at a time.
  #   Type: array.
  block_shape:
    - 512
    - 512
# Path to output log file (in addition to logging to `stderr`). Default logs to
#   `dolphin.log` within `work_directory`.
#   Type: string | null.
log_file:
# Time the config file was created.
#   Type: string.
creation_time_utc: '2024-12-14T21:24:57.514570Z'
# REQUIRED: list of CSLC files, or newline-delimited file containing list of CSLC files.
#   Type: array.
cslc_file_list:
  - /media/s/dolphin/slc/S1_007343_IW2_20201220T233809_VV_2084-BURST.tiff
  ...
output_options:
  # Output (x, y) resolution (in units of input data).
  #   Type: object | null.
  output_resolution:
  # Alternative to specifying output resolution: Specify the (x, y) strides (decimation
  #   factor) to perform while processing input. For example, strides of [4, 2] would turn an
  #   input resolution of [5, 10] into an output resolution of [20, 20].
  #   Type: object.
  strides:
    x: 4
    y: 2
  # Area of interest: [left, bottom, right, top] coordinates. e.g.
  #   `bbox=[-150.2,65.0,-150.1,65.5]`.
  #   Type: array | null.
  bounds:
    - 94.7
    - 29.56
    - 95.67
    - 29.87
  # Area of interest as a simple Polygon in well-known-text (WKT) format. Can pass a string,
  #   or a `.wkt` filename containing the Polygon text.
  #   Type: string | null.
  bounds_wkt:
  # EPSG code for the `bounds` or `bounds_wkt` coordinates, if specified.
  #   Type: integer.
  bounds_epsg: 4326
  # Options for `create_dataset` with h5py.
  #   Type: object.
  hdf5_creation_options:
    chunks:
      - 128
      - 128
    compression: gzip
    compression_opts: 4
    shuffle: true
  # GDAL creation options for GeoTIFF files.
  #   Type: array.
  gtiff_creation_options:
    - COMPRESS=lzw
    - ZLEVEL=4
    - BIGTIFF=yes
    - TILED=yes
    - INTERLEAVE=band
    - BLOCKXSIZE=128
    - BLOCKYSIZE=128
  # Whether to add overviews to the output GeoTIFF files. This will increase file size, but
  #   can be useful for visualizing the data with web mapping tools. See
  #   https://gdal.org/programs/gdaladdo.html for more.
  #   Type: boolean.
  add_overviews: true
  # List of overview levels to create (if `add_overviews=True`).
  #   Type: array.
  overview_levels:
    - 4
    - 8
    - 16
    - 32
    - 64
  # Specify an extra reference datetime in UTC. Adding this lets you to create and unwrap two
  #   single reference networks; the later resets at the given date (e.g. for a large
  #   earthquake event). If passing strings, formats accepted are YYYY-MM-
  #   DD[T]HH:MM[:SS[.ffffff]][Z or [±]HH[:]MM], or YYYY-MM-DD.
  #   Type: string | null.
  extra_reference_date:
ps_options:
  # Amplitude dispersion threshold to consider a pixel a PS.
  #   Type: number.
  amp_dispersion_threshold: 0.25
# Paths to existing Amplitude Dispersion file (1 per SLC region) for PS update calculation.
#   If none provided, computed using the input SLC stack.
#   Type: array.
amplitude_dispersion_files: []
# Paths to an existing Amplitude Mean files (1 per SLC region) for PS update calculation. If
#   none provided, computed using the input SLC stack.
#   Type: array.
amplitude_mean_files: []
# Paths to layover/shadow binary masks, where 0 indicates a pixel in layover/shadow, 1 is a
#   good pixel. If none provided, no masking is performed for layover/shadow.
#   Type: array.
layover_shadow_mask_files: []
phase_linking:
  # Size of the ministack for sequential estimator.
  #   Type: integer.
  ministack_size: 15
  # Maximum number of compressed images to use in sequential estimator. If there are more
  #   ministacks than this, the earliest CCSLCs will be left out of the later stacks. .
  #   Type: integer.
  max_num_compressed: 100
  # Index of input SLC to use for making phase linked interferograms after EVD/EMI.
  #   Type: integer.
  output_reference_idx: 0
  half_window:
    # Half window size (in pixels) for x direction.
    #   Type: integer.
    x: 11
    # Half window size (in pixels) for y direction.
    #   Type: integer.
    y: 5
  # Use EVD on the coherence instead of using the EMI algorithm.
  #   Type: boolean.
  use_evd: false
  # Beta regularization parameter for correlation matrix inversion. 0 is no regularization.
  #   Type: number.
  beta: 0.0
  # Snap correlation values in the coherence matrix below this value to 0.
  #   Type: number.
  zero_correlation_threshold: 0.0
  # Method for finding SHPs during phase linking.
  #   Type: string.
  #   Options: ['glrt', 'ks', 'rect', 'rect'].
  shp_method: glrt
  # Significance level (probability of false alarm) for SHP tests. Lower numbers include more
  #   pixels within the multilook window during covariance estimation.
  #   Type: number.
  shp_alpha: 0.001
  # If True, pixels labeled as PS will get set to NaN during phase linking to avoid summing
  #   their phase. Default of False means that the SHP algorithm will decide if a pixel should
  #   be included, regardless of its PS label.
  #   Type: boolean.
  mask_input_ps: false
  # StBAS parameter to include only nearest-N interferograms forphase linking. A
  #   `baseline_lag` of `n` will only include the closest`n` interferograms. `baseline_line`
  #   must be positive.
  #   Type: integer | null.
  baseline_lag:
  # Plan for creating Compressed SLCs during phase linking.
  #   Type: string.
  #   Options: ['always_first', 'first_per_ministack', 'last_per_ministack'].
  compressed_slc_plan: always_first
interferogram_network:
  # For single-reference network: Index of the reference image in the network.
  #   Type: integer | null.
  reference_idx: 0
  # Max `n` to form the nearest-`n` interferograms by index.
  #   Type: integer | null.
  max_bandwidth:
  # Maximum temporal baseline of interferograms.
  #   Type: integer | null.
  max_temporal_baseline:
  # For manual-index network: list of (ref_idx, sec_idx) defining the interferograms to form.
  #   Type: array | null.
  indexes:
unwrap_options:
  # Whether to run the unwrapping step after wrapped phase estimation.
  #   Type: boolean.
  run_unwrap: true
  # Whether to run Goldstein filtering step on wrapped interferogram.
  #   Type: boolean.
  run_goldstein: false
  # Whether to run interpolation step on wrapped interferogram.
  #   Type: boolean.
  run_interpolation: false
  # Phase unwrapping method.
  #   Type: string.
  #   Options: ['snaphu', 'icu', 'phass', 'spurt', 'whirlwind'].
  unwrap_method: snaphu
  # Number of interferograms to unwrap in parallel.
  #   Type: integer.
  n_parallel_jobs: 1
  # Set wrapped phase/correlation to 0 where mask is 0 before unwrapping. .
  #   Type: boolean.
  zero_where_masked: false
  preprocess_options:
    # Adaptive phase (Goldstein) filter exponent parameter.
    #   Type: number.
    alpha: 0.5
    # (for interpolation) Maximum radius to find scatterers.
    #   Type: integer.
    max_radius: 51
    # Threshold on the correlation raster to use for interpolation. Pixels with less than this
    #   value are replaced by a weighted combination of neighboring pixels.
    #   Type: number.
    interpolation_cor_threshold: 0.3
    # Threshold on the correlation raster to use for interpolation. Pixels with less than this
    #   value are replaced by a weighted combination of neighboring pixels.
    #   Type: number.
    interpolation_similarity_threshold: 0.3
  snaphu_options:
    # Number of tiles to split the inputs into using SNAPHU's internal tiling.
    #   Type: array.
    ntiles:
      - 1
      - 1
    # Amount of tile overlap (in pixels) along the (row, col) directions.
    #   Type: array.
    tile_overlap:
      - 0
      - 0
    # Number of tiles to unwrap in parallel for each interferogram.
    #   Type: integer.
    n_parallel_tiles: 1
    # Initialization method for SNAPHU.
    #   Type: string.
    #   Options: ['mcf', 'mst'].
    init_method: mcf
    # Statistical cost mode method for SNAPHU.
    #   Type: string.
    #   Options: ['defo', 'smooth'].
    cost: smooth
    # If True, after unwrapping with multiple tiles, an additional post-processing unwrapping
    #   step is performed to re-optimize the unwrapped phase using a single tile.
    #   Type: boolean.
    single_tile_reoptimize: false
  tophu_options:
    # Number of tiles to split the inputs into.
    #   Type: array.
    ntiles:
      - 1
      - 1
    # Extra multilook factor to use for the coarse unwrap.
    #   Type: array.
    downsample_factor:
      - 1
      - 1
    # Initialization method for SNAPHU.
    #   Type: string.
    #   Options: ['mcf', 'mst'].
    init_method: mcf
    # Statistical cost mode method for SNAPHU.
    #   Type: string.
    #   Options: ['defo', 'smooth'].
    cost: smooth
  spurt_options:
    # Temporal coherence to pick pixels used on an irregular grid.
    #   Type: number.
    temporal_coherence_threshold: 0.7
    # Similarity to pick pixels used on an irregular grid. Any pixel with similarity above
    #   `similarity_threshold` *or* above the temporal coherence threshold is chosen.
    #   Type: number.
    similarity_threshold: 0.5
    general_settings:
      # Tile up data spatially.
      #   Type: boolean.
      use_tiles: true
    tiler_settings:
      # Maximum number of tiles allowed.
      #   Type: integer.
      max_tiles: 64
      # Number of points used for determining tiles based on density.
      #   Type: integer.
      target_points_for_generation: 120000
      # Target points per tile when generating tiles.
      #   Type: integer.
      target_points_per_tile: 900000
      # Dilation factor of non-overlapping tiles. 0.05 would lead to 5 percent dilation of the
      #   tile.
      #   Type: number.
      dilation_factor: 0.05
    solver_settings:
      # Number of workers for temporal unwrapping in parallel. Set value to <=0 to let workflow
      #   use default workers (ncpus - 1).
      #   Type: integer.
      t_worker_count: 1
      # Number of workers for spatial unwrapping in parallel. Set value to <=0 to let workflow use
      #   (ncpus - 1).
      #   Type: integer.
      s_worker_count: 1
      # Temporal unwrapping operations over spatial links are performed in batches and each batch
      #   is solved in parallel.
      #   Type: integer.
      links_per_batch: 150000
      # Temporal unwrapping costs.
      #   Type: string.
      #   Options: ['constant', 'distance', 'centroid'].
      t_cost_type: constant
      # Scale factor used to compute edge costs for temporal unwrapping.
      #   Type: number.
      t_cost_scale: 100.0
      # Spatial unwrapping costs.
      #   Type: string.
      #   Options: ['constant', 'distance', 'centroid'].
      s_cost_type: constant
      # Scale factor used to compute edge costs for spatial unwrapping.
      #   Type: number.
      s_cost_scale: 100.0
      # Number of tiles to process in parallel. Set to 0 for all tiles.
      #   Type: integer.
      num_parallel_tiles: 1
    merger_settings:
      # Minimum number of overlap pixels to be considered valid.
      #   Type: integer.
      min_overlap_points: 25
      # Currently, only 'dirichlet' is supported.
      #   Type: dirichlet.
      method: dirichlet
      # Method used to estimate bulk offset between tiles.
      #   Type: string.
      #   Options: ['integer', 'L2'].
      bulk_method: L2
      # Number of interferograms to merge in one batch. Use zero to merge all interferograms in a
      #   single batch.
      #   Type: integer.
      num_parallel_ifgs: 3
timeseries_options:
  # Whether to run the inversion step after unwrapping, if more than  a single-reference
  #   network is used.
  #   Type: boolean.
  run_inversion: true
  # Norm to use during timeseries inversion.
  #   Type: string.
  #   Options: ['L1', 'L2'].
  method: L2
  # Reference point (row, col) used if performing a time series inversion. If not provided, a
  #   point will be selected from a consistent connected component with low amplitude
  #   dispersion.
  #   Type: array | null.
  reference_point:
  # Run the velocity estimation from the phase time series.
  #   Type: boolean.
  run_velocity: true
  # Pixels with correlation below this value will be masked out.
  #   Type: number.
  correlation_threshold: 0.2
  # Size (rows, columns) of blocks of data to load at a time. 3D dimsion is number of
  #   interferograms (during inversion) and number of SLC dates (during velocity fitting).
  #   Type: array.
  block_shape:
    - 256
    - 256
  # Number of parallel blocks to process at once.
  #   Type: integer.
  num_parallel_blocks: 4
correction_options:
  # List of weather-model files (one per date) for tropospheric corrections.
  #   Type: array.
  troposphere_files: []
  # Format of dates contained in weather-model filenames.
  #   Type: string.
  tropo_date_fmt: '%Y%m%d'
  # Package for tropospheric correction. Choices: pyaps, raider.
  #   Type: string.
  tropo_package: pyaps
  # Enumeration representing different tropospheric models.
  #   Type: string.
  #   Options: ['ECMWF', 'ERA5', 'HRES', 'ERAINT', 'ERAI', 'MERRA', 'NARR', 'HRRR', 'GMAO'].
  tropo_model: ERA5
  # Type of tropospheric delay.
  #   Type: string.
  #   Options: ['wet', 'dry', 'hydrostatic', 'comb'].
  tropo_delay_type: comb
  # List of GNSS-derived TEC maps for ionospheric corrections (one per date). Source is
  #   https://cddis.nasa.gov/archive/gnss/products/ionex/.
  #   Type: array.
  ionosphere_files: []
  # Line-of-sight geometry files for each burst/SLC stack area, for use in correction
  #   computations.
  #   Type: array.
  geometry_files: []
  # DEM file for tropospheric/ topographic phase corrections.
  #   Type: string | null.
  dem_file:)

dolphin version: 0.33.0

Python deps:
        h5py: 3.11.0
         jax: 0.4.37
       numba: 0.60.0
       numpy: 1.26.4
 opera-utils: 0.14.0
    pydantic: 2.10.2
      pyproj: 3.7.0
    rasterio: 1.4.2
 ruamel.yaml: 0.18.6
       scipy: 1.13.1
threadpoolctl: 3.5.0
        tqdm: 4.66.5
  osgeo.gdal: 3.9.3

System:
      python: 3.12.2 | packaged by conda-forge | (main, Feb 16 2024, 20:50:58) [GCC 12.3.0]
  executable: /home/s/anaconda3/envs/sentinel/bin/python
     machine: Linux-5.15.0-126-generic-x86_64-with-glibc2.31
Unwrapping packages:
      snaphu: 0.4.1
       spurt: None
       isce3: 0.24.1
       tophu: 0.2.1
   whirlwind: None
optional GPU info:
         jax: 0.4.37
gpu_is_available: True
None

<\details>

**Comment by scottstanie** [comment]
How did you get these input files? The SLCs need to be registered to the same grid and therefore be the same shape

**Comment by songzwgithub** [comment]
Thank you for your reply. I downloaded SLCs from ASF S1 Bursts. I just realized that this is not a registered product.

**Comment by scottstanie** [comment]
Ok that's what I thought it might be. 
Yes you have to run them through some stack processor like isce2/isce3/gamma

**Comment by songzwgithub** [comment]
> Ok that's what I thought it might be. Yes you have to run them through some stack processor like isce2/isce3/gamma

Thanks! I will try it.

**Comment by scottstanie** [comment]
Let me know if there's more difficulty here, but I'll assume this is an issue prior to dolphin. 
We may consider adding it to the FAQ if that gets made
